### PR TITLE
Fix corner case that would result in panic

### PR DESCRIPTION
**Pull request by conradoplg**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description

Fixes a panic that would be raised by trying to create an invalid date (e.g. 2021-02-30) when computing the interval between e.g.  Jan 30 and Mar 1 (it would try to compute the days between "Feb 30" and Mar 1)

I'm not sure what's the best behaviour in this case, there is no definitive answer. This PR simply tries previous days until it finds a valid day. So in the example above it would compute the days between Feb 28 and Mar 1, returning 1 month and 1 day. Note that between Jan 29 and Mar 1 it would also return 1 month and 1 day, as well as Jan 28 and Mar 1.

### CODE REVIEW

**Comment by gpgkd906** [comment]
@conradoplg 
thanks!

**Comment by gpgkd906** [comment]
@conradoplg 

thanks for your pull-request.
Although the pull-request was merged, I thought about it again. 
When an invalid date is coming, I think maybe we should return an ```Result<Error>``` instead of trying to calculate.

Actually, the following sentence will be panic! before it run into the calculate method.

```rust
let date1 = Utc.ymd(2021, 2, 30).and_hms(0, 0, 0); // panic here
let date2 = Utc.ymd(2022, 3, 1).and_hms(0, 0, 0);

let date_interval = calculate(&date1, &date2);
```
How can we create an invalid date?

**Comment by conradoplg** [comment]
@gpgkd906 that's true, but in that case the user is trying to provide the invalid date. I think it is a valid assumption that the input dates are valid. (We have to assume that, since you can't actually create an invalid date).

I can't come up with any scenarios where it's impossible to calculate the interval between two valid dates. (There are probably some, though :sweat_smile: )

The problem that this PR fixed was caused by `date_component` creating an invalid date in the middle of the computation. For example, trying to compute the interval between Jan 30 and Mar 1 (which are valid dates), the library had to instantiate a "Feb 30" date in the middle of the computation. With the fix, that no longer occurs.

**Comment by gpgkd906** [comment]
@conradoplg 
>trying to compute the interval between Jan 30 and Mar 1 (which are valid dates), the library had to instantiate a "Feb 30" date in the middle of the computation. With the fix, that no longer occurs

Oh, I got it.
thank you!

**Pull request merged**
